export const RESTAURANTS_LIST = [
  {
    id: 1,
    resName: "Belgian Waffles",
    cuisine: "Desserts, Pancackes, Waffles, Sugar, SWeet",
    rating: 4.3,
    deliveryTime: 38,
    uri: "https://lh3.googleusercontent.com/ANN1yUNcxcptq2rufgheBzxw9gEe7kB3odMRGREli2IO0fCsnWKgq5KGVuquLT6ZUAeWuGaVZdphHmN1xCWcf0ga661perJtXQC0EyF9",
  },
  {
    id: 2,
    resName: "Udupi Palace",
    cuisine: "North Indian, South Indian",
    rating: 4.1,
    deliveryTime: 18,
    uri: "https://lh3.googleusercontent.com/-FTJCTVzvTVyoZ1Xb_POHDCKdoaXbdYhfHBrm3cq3BBSqRrY2IRqIEBBgtXtqZI34K14MXza3lFywOPZlDDDb-s2Vg=w512-rw",
  },
  {
    id: 3,
    resName: "Burger King",
    cuisine: "Burger, Fast Food, Shakes",
    rating: 1.2,
    deliveryTime: 22,
    uri: "https://www.pngmart.com/files/5/Hamburger-PNG-Pic.png",
  },
  {
    id: 4,
    resName: "McDonalds",
    cuisine: "Fast Food, Ice Cream",
    rating: 3.3,
    deliveryTime: 28,
    uri: "https://freepngimg.com/thumb/burger/146698-king-cheese-burger-free-photo.png",
  },
  {
    id: 5,
    resName: "TBT Shakes",
    cuisine: "ICe Cream, Shakes",
    rating: 4.8,
    deliveryTime: 11,
    uri: "https://i.pinimg.com/564x/e8/a9/da/e8a9dacde48f8e5aa0f9004947b5eb05.jpg",
  },
  {
    id: 6,
    resName: "Naturals Ice Cream",
    cuisine: "Sundaes",
    rating: 2.3,
    deliveryTime: 48,
    uri: "https://lh3.googleusercontent.com/GRfjxx3WwIc3RGpwSXUADa9D65Td_fwMPxAtPkNQDOQsw4rsT6-d4JSghR3Mcj-kWU5aktbwbSRMWtYgXAQTVwHRPzb6WTsNIxDO7KS-OA=w512-rw",
  },
  {
    id: 7,
    resName: "Truffles",
    cuisine: "Burgers, Chinese, Continental",
    rating: 4.7,
    deliveryTime: 58,
    uri: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOkZQbPgPEQdXaxd08q8jOHzS2OgsCPrxr5BDEIiShjzvtMna06kuk1uYPJemnLRvBuMM&usqp=CAU",
  },
  {
    id: 8,
    resName: "Leo's Burger",
    cuisine: "Fast Food, Burger",
    rating: 4.1,
    deliveryTime: 44,
    uri: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/food-design-template-80c03cad7c57e1d55c0ed92f66cbced9_screen.jpg?ts=1647231858",
  },
  {
    id: 9,
    resName: "Oven Story Pizza",
    cuisine: "Pizza, Pasta",
    rating: 3.7,
    deliveryTime: 11,
    uri: "https://media.istockphoto.com/id/1032111568/photo/square-crust-flatbread-pizza.jpg?s=612x612&w=0&k=20&c=yssQ1TkcUG_BOAARHuWyf0k1x-emNtlGICP0_FxY2m8=",
  },
  {
    id: 10,
    resName: "Margerita stories",
    cuisine: "Pizza",
    rating: 2.7,
    deliveryTime: 19,
    uri: "https://media.istockphoto.com/id/1354959335/photo/square-pizza-inside-its-box-on-a-gray-background.jpg?s=612x612&w=0&k=20&c=-0e1YBN4bxbALqPWb9CSTQYtFfJYY6_zeYfI2p17aT0=",
  },
  {
    id: 11,
    resName: "Yummy Pasta",
    cuisine: "Pasta",
    rating: 4.9,
    deliveryTime: 51,
    uri: "https://unsophisticook.com/wp-content/uploads/2017/08/Kitchen-Sink-Pasta-Square.jpg",
  },
  {
    id: 12,
    resName: "Chinese Villa",
    cuisine: "Chinese",
    rating: 3.9,
    deliveryTime: 22,
    uri: "https://img.freepik.com/premium-psd/chinese-food-promotion-instagram-post-square-web-banner-social-media-template_585641-309.jpg",
  },
  {
    id: 13,
    resName: "Noodles Paradise",
    cuisine: "Chinese, Continental",
    rating: 4.2,
    deliveryTime: 40,
    uri: "https://www.deliciousmagazine.co.uk/wp-content/uploads/2017/01/laundry.jpg",
  },
];
